const pasturas = [
    {   especie: 'Ryegrass',
        habito: 'Anual',
        ciclo: 'Invernal',
        siembra: 'Abril',
        densidad: '20',
        costo: '2,00',
        id: 1
    },
    {   especie: 'Avena',
        habito: 'Anual',
        ciclo: 'Invernal',
        siembra: 'Marzo',
        densidad: '90',
        costo: '0,60',
        id: 2
    },
    {   especie: 'Achicoria',
        habito: 'Anual',
        ciclo: 'Invernal',
        siembra: 'Marzo',
        densidad: '5',
        costo: '8,50',
        id: 3
    },
    {   especie: 'Sorgo',
        habito: 'Anual',
        ciclo: 'Estival',
        siembra: 'Noviembre',
        densidad: '15',
        costo: '1,50',
        id: 4
    },
    {   especie: 'Sudangras',
        habito: 'Anual',
        ciclo: 'Estival',
        siembra: 'Noviembre',
        densidad: '18',
        costo: '1,60',
        id: 5
    },
    {   especie: 'Moha',
        habito: 'Anual',
        ciclo: 'Estival',
        siembra: 'Noviembre',
        densidad: '15',
        costo: '1,05',
        id: 6
    },
    {   especie: 'Ryegrass Perenne',
        habito: 'Perenne',
        ciclo: 'Invernal',
        siembra: 'Abril',
        densidad: '15',
        costo: '2,50',
        id: 7
    },
    {   especie: 'Festuca',
        habito: 'Perenne',
        ciclo: 'Invernal',
        siembra: 'Marzo',
        densidad: '12',
        costo: '2,70',
        id: 8
    },
    {   especie: 'Dactylis',
        habito: 'Perenne',
        ciclo: 'Invernal',
        siembra: 'Marzo',
        densidad: '10',
        costo: '3,00',
        id: 9
    },
    {   especie: 'Trebol Blanco',
        habito: 'Perenne',
        ciclo: 'Invernal',
        siembra: 'Marzo',
        densidad: '2',
        costo: '8,50',
        id: 10
    },
    {   especie: 'Lotus Corniculatus',
        habito: 'Perenne',
        ciclo: 'Invernal',
        siembra: 'Marzo',
        densidad: '5',
        costo: '8,00',
        id: 11
    }

]